Api 158/add endpoints webhooks doc
conekta/openapi pull request #22
Opened 2023-05-17 13:14 UTC by MaritzaGarc

Missing endpoints documentation webhooks:

webhooks/:id/test
events/:event_id/webhook_logs/:webhook_log_id/resend

2023-05-17 13:50 UTC, fcarrero commented on parameters/commons/path_param/webhook_log_id.yml
> +name: "webhook log id"
```suggestion
name: "webhook_log_id"
```

2023-05-17 13:52 UTC, fcarrero commented on resources/events/events_webhook_resend.yml
> +    - Events
@leofischer  @jalonsoDevConekta 
este endpoint lo ven mas del lado de webhook o events ?

2023-05-17 13:53 UTC, fcarrero commented on schemas/webhooks/webhook_test_response.yml
> +  id:
porfa agreguemos description a cada campo

2023-05-17 13:54 UTC, fcarrero commented on resources/events/events_webhook_resend.yml
> +    401:
esto es mas pregunta/duda
existe algún otro status code error que se podría dar en este flujo ?

2023-05-17 13:54 UTC, fcarrero commented on resources/events/events_webhook_resend.yml
> +    "200":
```suggestion
    200:
```

2023-05-17 13:54 UTC, fcarrero commented on parameters/commons/path_param/event_id.yml
> +description: identifier event
```suggestion
description: event identifier
```

2023-05-17 14:02 UTC, fcarrero commented on schemas/webhooks/webhook_test_response.yml
> +title: webhook_test_response
este modelo se parece mucho a https://github.com/conekta/openapi/blob/4453f26cd00063204d2ecaac2c5431fbca3fd926/schemas/webhooks/webhook_response.yml

existen diferencias entre ambos ?

2023-05-17 14:49 UTC, MaritzaGarc commented on schemas/webhooks/webhook_test_response.yml
> +title: webhook_test_response
Sólo hay diferencia en una propiedad: **deleted** en webhook_response, webhook_test_response no tiene esa propiedad.

2023-05-17 14:51 UTC, fcarrero commented on schemas/webhooks/webhook_test_response.yml
> +title: webhook_test_response
considero que es el mimo modelo, 
@leofischer como lo ves ? hace falta el deleted en el primer modelo ?

2023-05-17 15:40 UTC, jalonsoDevConekta commented on resources/events/events_webhook_resend.yml
> +    - Events
puede evolucionar a un events/:id/resend y necesitamos otro que no este ligado al webhook_log sino  a un webhook id para que podamos enviar un evento a un webhook en específico(ya sea nuevo o viejo)

2023-05-17 20:39 UTC, leofischer requested changes

2023-05-17 20:39 UTC, leofischer commented on _build/api.yaml
> +        "401":
no podemos aprovechar algún template para minimizar el esfuerzo de mantenimiento como haces [aquí](https://github.com/conekta/openapi/pull/22/files#diff-29d94ed372c04fe75b71f053d6512964e4bfb29acb6437259020adb4130937c1R15)?

2023-05-17 20:42 UTC, fcarrero commented on _build/api.yaml
> +        "401":
no entendi

2023-05-18 13:30 UTC, fcarrero commented on schemas/webhooks/webhook_test_response.yml
> +title: webhook_test_response
@MaritzaGarc creo que hace falta agregar este field

2023-05-18 14:13 UTC, leofischer approved these changes

2023-05-18 15:28 UTC, MaritzaGarc commented on schemas/webhooks/webhook_test_response.yml
> +title: webhook_test_response
Elimine el modelo que habia creado webhook_test_response.yml e hice uso del modelo webhook_response.yml

2023-05-18 16:16 UTC, fcarrero approved these changes

2023-05-18 17:12 UTC, leofischer commented on _build/api.yaml
> +        "401":
perdón, veo que eso era el build, ignoramos este comentario

2023-05-19 15:29 UTC, merged