[API-193] - add endpoints api keys
conekta/openapi pull request #25
Opened 2023-05-19 15:00 UTC by MaritzaGarc

add endpoints api keys 
![Captura de pantalla 2023-05-19 a la(s) 9 59 44 a m](https://github.com/conekta/openapi/assets/89799858/a2e253d7-3550-4f2a-8a19-5a4b0b07de46)

2023-05-19 21:59 UTC, leofischer commented on schemas/api_keys/api-key_create_response.yml
> +  id:
Estaría bien dejar todo ordenado de forma alfabético

2023-05-19 21:59 UTC, leofischer commented on api.yaml
> +    $ref: "./resources/events/events_resend.yml"
en casos futuros estaría bien separar mejoras ajenas en otros PRs

2023-05-19 22:02 UTC, MaritzaGarc commented on api.yaml
> +    $ref: "./resources/events/events_resend.yml"
Gracias @Leo, lo tendré presente.

2023-05-22 15:16 UTC, jalonsoDevConekta approved these changes

2023-05-22 21:30 UTC, nicocedron approved these changes

2023-05-23 16:04 UTC, leofischer approved these changes
🚀

2023-05-23 16:10 UTC, fcarrero requested changes
revisando el pr

2023-05-23 16:21 UTC, fcarrero commented on resources/api_keys/api_keys.yml
> +                  total:
pense que total estaba deprecado en la 2.1 
@conekta/core

2023-05-23 16:27 UTC, fcarrero commented on api.yaml
> +    $ref: "./resources/events/events_resend.yml"
para la proxíma vez tener en cuenta que estos renames hacen cambios en los sdks y generan breaking changes (afortunadamente aun no hemos lanzamos versiones recientes)

2023-05-23 16:27 UTC, fcarrero commented on resources/events/events_resend.yml
> +  operationId: resendEvent
para la proxíma vez tener en cuenta que estos renames hacen cambios en los sdks y generan breaking changes (afortunadamente aun no hemos lanzamos versiones recientes)

2023-05-23 16:28 UTC, fcarrero commented on resources/events/events_resend.yml
> -            $ref: ../../schemas/events/events_webhook_resend_response.yml
para la proxíma vez tener en cuenta que estos renames hacen cambios en los sdks y generan breaking changes (afortunadamente aun no hemos lanzamos versiones recientes)

2023-05-23 18:28 UTC, jalonsoDevConekta commented on resources/api_keys/api_keys.yml
> +                  total:
si

2023-05-23 18:28 UTC, jalonsoDevConekta commented on resources/api_keys/api_keys.yml
> +  description: "Consume the list of api keys you have"
si, deberia ser igual que todos los recursos

2023-05-23 19:10 UTC, MaritzaGarc commented on api.yaml
> +    $ref: "./resources/events/events_resend.yml"
Lo tendré presente, gracias.

2023-05-23 19:10 UTC, MaritzaGarc commented on resources/events/events_resend.yml
> +  operationId: resendEvent
Lo tendré presente, gracias.

2023-05-23 19:10 UTC, MaritzaGarc commented on resources/events/events_resend.yml
> -            $ref: ../../schemas/events/events_webhook_resend_response.yml
Lo tendré presente, gracias.

2023-05-23 20:20 UTC, fcarrero commented on schemas/api_keys/api-key_response.yml
> +title: api_key_response
cual es la diferente de este modelo vs schemas/api_keys/api-key_response.yml ?

2023-05-23 20:21 UTC, fcarrero commented on resources/api_keys/api_key.yml
> +  description: "update an existing api Key"
```suggestion
  description: "Update an existing api Key"
```

2023-05-23 20:22 UTC, fcarrero commented on resources/api_keys/api_key.yml
> +              description: Indicates if the webhook key is active
Creo que aca la description no va de acuerdo al campo

2023-05-23 20:23 UTC, fcarrero commented on schemas/api_keys/api-key_response.yml
> +    description: Indicates if the api key is public or private
la description es la correcta ?

2023-05-23 20:24 UTC, fcarrero commented on schemas/api_keys/api-key_response.yml
> +    type: integer
si el prefix es key__xxx
el tipo no seria string ?

2023-05-23 20:25 UTC, fcarrero commented on schemas/api_keys/api-key_create_response.yml
> +  prefix:
mismo que comentarios abajo

2023-05-23 20:25 UTC, fcarrero commented on schemas/api_keys/api-key_create_response.yml
> +  role:
mismo que comentarios abajo

2023-05-23 22:41 UTC, fcarrero commented on resources/api_keys/api_key.yml
> +                    example: true
porfavor agregar description

2023-05-23 22:42 UTC, fcarrero commented on resources/api_keys/api_keys.yml
> +              - $ref: ../../schemas/pagination/pagination.yml
creo que hace falta el schema de page.yml
```json
{
    "next_page_url": null,
    "previous_page_url": null,
    "has_more": false,
    "object": "list",
    "data": [
        {
            "active": true,
            "description": "Llave generada producción-privada",
            "livemode": true,
            "prefix": "key_89",
            "id": "xxxx",
            "object": "api_key",
            "created_at": 1684340566,
            "deactivated_at": null,
            "deleted": null,
            "authentication_token": null,
            "role": "private"
        },
        {
            "active": true,
            "description": "Llave generada producción-pública",
            "livemode": true,
            "prefix": "key_RR",
            "id": "xxxxx",
            "object": "api_key",
            "created_at": 1684340566,
            "deactivated_at": null,
            "deleted": null,
            "authentication_token": null,
            "role": "public"
        }
    ]
}
```

2023-05-23 22:43 UTC, fcarrero commented on resources/api_keys/api_key.yml
> +                  deleted:
haciendo un getall veo que el deleted tambien vienen en el objeto , no solo viene en el delete path
se podria agregar a la response ??

```json
{
    "next_page_url": null,
    "previous_page_url": null,
    "has_more": false,
    "object": "list",
    "data": [
        {
            "active": true,
            "description": "Llave generada producción-privada",
            "livemode": true,
            "prefix": "key_89",
            "id": "xxxxx",
            "object": "api_key",
            "created_at": 1684340566,
            "deactivated_at": null,
            "deleted": null,
            "authentication_token": null,
            "role": "private"
        },
        {
            "active": true,
            "description": "Llave generada producción-pública",
            "livemode": true,
            "prefix": "key_RR",
            "id": "xxxxx",
            "object": "api_key",
            "created_at": 1684340566,
            "deactivated_at": null,
            "deleted": null,
            "authentication_token": null,
            "role": "public"
        }
    ]
}
```

2023-05-23 22:46 UTC, fcarrero commented on resources/api_keys/api_keys.yml
> +              - $ref: ../../schemas/pagination/pagination.yml
los fields `deactivated_at` y `authentication_token` se podrían agregar  ? no los ves necesarios ?
que opinas ?

2023-05-24 15:10 UTC, fcarrero approved these changes

2023-05-24 15:39 UTC, merged